### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by jsncepu** [erihsu/Sym-CTS#5]
Hello, when I run flow.py, it reported that line 199 in construction.py has an error: wire_list.append(wire(new_startpoint,new_endpoint))
UnboundLocalError: local variable 'new_startpoint' referenced before assignment. Would you please give me a hint to handle this problem? Thanks!

**Comment by erihsu** [comment]
> Hello, when I run flow.py, it reported that line 199 in construction.py has an error: wire_list.append(wire(new_startpoint,new_endpoint))
> UnboundLocalError: local variable 'new_startpoint' referenced before assignment. Would you please give me a hint to handle this problem? Thanks!

I wil check it when I am quite free. As I have leave this project for a long time, I will review it.

**Comment by jsncepu** [comment]
> > Hello, when I run flow.py, it reported that line 199 in construction.py has an error: wire_list.append(wire(new_startpoint,new_endpoint))
> > UnboundLocalError: local variable 'new_startpoint' referenced before assignment. Would you please give me a hint to handle this problem? Thanks!
> 
> I wil check it when I am quite free. As I have leave this project for a long time, I will review it.

Thank you for your reply. I tried to declare new_startpoint and new_endpoint as global variables within the function and then the script worked. However, after running the flow.py, I found that some nodes of the clock tree don't be connected. The number of wires is less than the one that it should be. In other words, the flow.py only generates an incomplete tree.

**Comment by erihsu** [comment]
I should notice that liberty file is not included in the repo and you can not experience the buffer insertion optimization if you want to try

**Comment by erihsu** [comment]
@jsncepu 
Should work now
